name: create-release
on:
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Next Version
        id: version
        uses: codacy/git-version@2.4.0
        with:
          # The name of the release branch
          release-branch: main
          log-paths: ./
          prefix: ''
        
      - name: Create draft release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ steps.version.outputs.version }} --draft --generate-notes --target main

