name: create-release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
  
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ inputs.version }} --draft

