name: create-release
on:
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history      

      - name: Get Next Version
        id: version
        uses: codacy/git-version@2.4.0
        with:
          # The name of the release branch
          release-branch: main
          log-paths: ./
          prefix: ''
        
      - name: Create draft release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ steps.version.outputs.version }} --draft --generate-notes --target main

  publish-release:
    runs-on: ubuntu-latest
    needs: create-release
    environment: release
    steps:
      - uses: actions/checkout@v3
      - name: publish release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release edit ${{ needs.create-release.outputs.version }} --draft=false

